// Generated by CoffeeScript 1.6.3
var componentDefinition, link, main;

link = function(CorespringContainer, $sce) {
  return function(scope, element, attrs) {
    scope.inputType = 'checkbox';
    scope.answer = {
      choices: {}
    };
    scope.$watch('session', function(newValue) {
      if (newValue == null) {
        return;
      }
      return scope.sessionFinished = newValue.isFinished;
    }, true);
    scope.$watch('question.config.singleChoice', function(newValue) {
      return scope.inputType = !!newValue ? "radio" : "checkbox";
    });
    scope.containerBridge = {
      setModel: function(model) {
        scope.question = model;
        return scope.inputType = !!model.config.singleChoice ? "radio" : "checkbox";
      },
      setAnswer: function(answer) {
        var key, _i, _len;
        console.log("Setting answer to", answer);
        if (answer.length === 1) {
          scope.answer.choice = "" + answer[0];
        } else {
          for (_i = 0, _len = answer.length; _i < _len; _i++) {
            key = answer[_i];
            scope.answer.choices[key] = true;
          }
        }
        console.log(scope.answer.choices);
        return console.log(scope.answer.choice);
      },
      getAnswer: function() {
        var key, out, selected, _ref;
        out = [];
        if (scope.answer.choice) {
          out.push(scope.answer.choice);
        } else {
          _ref = scope.answer.choices;
          for (key in _ref) {
            selected = _ref[key];
            if (selected) {
              out.push(key);
            }
          }
        }
        return out;
      },
      setSession: function(session) {
        return scope.session = session;
      },
      setResponse: function(response) {
        scope.response = response;
        console.log("set response for single-choice", response);
        if (response.feedback) {
          return _.each(response.feedback, function(fb) {
            var choice;
            choice = _.find(scope.question.choices, function(c) {
              return c.value === fb.value;
            });
            if (choice != null) {
              choice.feedback = fb.feedback;
            }
            if (choice != null) {
              choice.correct = fb.correct;
            }
            return console.log("choice: ", choice);
          });
        }
      }
    };
    return CorespringContainer.register(attrs['id'], scope.containerBridge);
  };
};

main = [
  'CorespringContainer', '$sce', function(CorespringContainer, $sce) {
    var def;
    def = {
      scope: 'isolate',
      restrict: 'E',
      replace: true,
      link: link(CorespringContainer, $sce),
      template: "<div class=\"view-single-choice\">\n  <style>\n    .view-single-choice  .feedback.incorrect {\n      border: solid 1px red;\n    }\n\n    .view-single-choice  .feedback.correct {\n      border: solid 1px green;\n    }\n  </style>\n  <label ng-bind-html-unsafe=\"question.prompt\"></label>\n\n  <div ng-repeat=\"o in question.choices\">\n    <label>{{o.label}}</label>\n              <span ng-switch=\"inputType\">\n              <input ng-switch-when=\"checkbox\" type=\"checkbox\" ng-disabled=\"sessionFinished\" name=\"group\"\n                     ng-value=\"o.label\" ng-model=\"answer.choices[o.value]\"></input>\n              <input ng-switch-when=\"radio\" type=\"radio\" ng-disabled=\"sessionFinished\" name=\"group\" ng-value=\"o.value\"\n                     ng-model=\"answer.choice\"></input>\n              </span>\n\n              <span\n                class=\"cs-feedback\"\n                ng-class=\"{true:'correct', false:'incorrect'}[o.correct]\"\n                ng-show=\"o.feedback\">{{o.feedback}}</span>\n  </div>\n</div>"
    };
    return def;
  }
];

componentDefinition = {
  framework: 'angular',
  directive: main
};
